= Assigning Permissions 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform comes with predefined permissions that you can set in Anypoint Access Management to provide users with different access levels. You configure the permissions for administrators and Exchange viewers. 

The Salesforce platform uses the System Administrator profile which contains all of the permissions to perform specific tasks on the Experience Cloud. For API Experience Hub, this profile is required for the user who installs and manages the Salesforce organization.


== Before You Begin
Consider which user in your organization you want to perform the administrator tasks.

== Grant the API Experience Hub Administrator Permission
The Organization Administration and API Experience Hub Administrator can perform all of the functions to create a portal. Only the Organization Administrator or an existing API Experience Hub Administrator can grant a user the API Experience Hub Administrator permission. Grant this permission when you want another user in your organization to perform the Salesforce linking process, create and curate the portal, manage the portal, and manage users.

To grant the API Experience Hub Administrator permission to a user:

. Log in to Anypoint Platform using an account with the Organization Administrator permission.
. Click *Access Management*.
. Click *Users*.
. Click the username of the user that you want to add the API Experience Hub Administrator permission. 
. Select *Permissions* and click *Add Permissions*.
. From the *Select permissions to add for this user* search box, enter *API Experience Hub Amin* and select the checkbox.
. Click the blue plus icon.

//=== Grant the API Experience Hub Portal Administrator Permission 

//If there is more than one users that manages the portal, you can grant another user within your organization the API Experience Hub Portal Administrator permission.

//. From *Access Management*, click *Users*.
//. Click the username of the user that you want to add the API Experience Hub Administrator permission. 
//. Select *Permissions* and click *Add Permissions*.
//. From the *Select permissions to add for this user* search box, enter *API Experience Hub Portal Amin* and select the checkbox.
//. Click the blue plus icon.

== Grant the Exchange Viewer Permission

Administrators can only add APIs for which they have the Exchange Viewer permission. All administrators must have the Exchange Viewer permission to add APIs to the portal.

When APIs are added to the portal, all administrators are assigned automatically the Exchange Viewer permission for the APIs added in the portal. 

To grant the Exchange Viewer permission to a user:

. From *Access Management*, click *Users*.
. Click the username of the user that you want to add the Exchange Viewers permission. 
. Select *Permissions* and click *Add Permissions*.
. From the *Select permissions to add for this user* search box, enter *Exchange Viewers* and select the checkbox.
. Click the blue plus icon.

== Apply the Principle of Least Privilege for Your Salesforce Organization
To install the managed package and operate within the Salesforce organization, a user with the System Administrator profile is required. This user connects the Salesforce Experience Cloud to link the Salesforce organization with the Anypoint Platform organization. The System Administrator profile might have more permissions than necessary. For users with an existing Salesforce organization and potentially sensitive data, ensure the security of that data by following the principle of least privilege. For API Experinence Hub, you can create a permission set named AEH_Anypoint, add all the necessary permissions, and assign the permission set to the a user who performs the linking process.

=== AEH_Anypoint Permission Set


The permission set must have the following permissions:

* System
** Apex REST Services
**  API Enabled
** Assign Topics
** Author Apex
** Connect Organization to Environment Hub
** Create and Customize Dashboards
** Create and Customize List Views
** Create and Customize Reports
**  Create and Set Up Experiences
** Create Dashboard Folders
** Create Report Folders
** Create Topics
** Customize Application
** Delete Topics
**  Download AppExchange Packages
** Edit Events
**  Edit HTML Templates
** Edit My Dashboards
**  Edit My Reports
**  Edit Tasks
**  Edit Topics
**  Manage Auth. Providers
** Manage Connected Apps
** Manage Custom Permissions
**  Manage Dashboards in Public Folders
** Manage Letterheads
** Manage Multi-Factor Authentication in User Interface
** Manage Public Classic Email Templates
** Manage Public Documents
** Manage Public List Views
** Manage Reports in Public Folders
**  Manage Session Permission Set Activations
** Modify All Data
**  Modify Metadata Through Metadata API Functions
**  Run Reports
** Transfer Record
** View All Data
** View Dashboards in Public Folders
** View Event Log Files
** View Login Forensics Events
** View Real-Time Event Monitoring Data
** View Reports in Public Folders
** View Roles and Role Hierarchy
** View Setup and Configuration

* User
** Assign Permission Sets
** Manage Internal Users
** Manage IP Addresses
** Manage Login Access Policies
** Manage Password Policies
** Manage Profiles and Permission Sets
** Manage Roles
** Manage Sharing
** Manage Users
** Reset User Passwords and Unlock Users
** View All Users






== See Also

* xref:connecting-to-salesforce.adoc[Connecting to Salesforce]