= Assigning Permissions 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform comes with predefined permissions that you can set in Anypoint Access Management to provide users with different access levels. You can configure the permissions for administrators and Exchange viewers. 

The Salesforce platform uses the System Administrator profile which contains all of the permissions to perform specific tasks on the Experience Cloud. For API Experience Hub, this profile is required for the user who installs and manages the Salesforce organization.

== Users, Roles, and Permissions
There are roles and permissions that you set in Access Management to manage users with different access levels. API Experience Hub has permissions for administrators, consumers, and Exchange viewers. For more information, see xref:access-management::managing-permissions.adoc[Managing Permissions in Access Management].


=== Administrator Roles, Permissions, and Profiles

The Organization Administrator role has all of the permissions necessary to create, curate, manage, and customize a portal. This role can also grant another user in their organization the API Experience Hub Administrator permission. This permission enables a user to do all of the same tasks in the portal as the Organization Administrator.

//If there is more than one user who intends to curate and manage the portal, the Organization Administrator can grant another user the API Experience Hub Portal Administrator permission. This administrator has fewer permissions in the portal than the Organization Administrator and the API Experience Hub Administrator.

An API Experience Hub Admin team and an API Experience Hub Portal Admin team is created during the connecting and linking process. Once your Salesforce organization is successfully connected to your Anypoint organization, the AEH Admin team is created. After the Salesforce linking process is complete, any user, who is assigned the AEH Admin, is automatically added to the AEH Admin team. 

Once your styling changes for the portal are saved, the AEH Portal Admin team is created. Although the API Experience Hub Portal Administrator team is visible in Access Management, this permission is not supported in this release.

Administrators can only add APIs for which they have the Exchange Viewer permission. When APIs are added to the portal, all administrators are automatically assigned the Exchange Viewer permission. 

Administrators access the Salesforce Experience Builder with a shared user account. The identity of the administrator is shared therefore, API Experience Hub cannot determine the individual administrator's action in the shared account. 

==== Salesforce System Administrator Profile
API Experience Hub is integrated with Salesforce Experience Cloud. The System Administrator profile has specific permissions to perform functions on the Salesforce platform. The user with this profile performs the initial step of creating an API portal by connecting to the Salesforce Experience Cloud and linking theSalesforce organization to the Anypoint organization. This process can only be done by the Salesforce user with the System Administrator profile.

|===
|Role/Permission/Profile |Description |Actions
|Organization administrator in the main organization|API Experience Hub is business group agnostic which means that the portal belongs to the main organization only and the admin can create portals across business groups. The organization administrator inherits all API Experience Hub permissions, enabling them to perform any available operation within the platform.
a|
* Perform the Salesforce linking process
* Create a portal
* Add and remove APIs from the portal
* Assign the visibility of an API instance
* Manage users
* Use Experience Builder to customize portal
|API Experience Hub Administrator|The admin inherits all of the Organization Administrator permissions necessary to create your API Portal. 
a|
* Perform the Salesforce linking process
* Create a portal
* Add and remove APIs from the portal
* Assign the visibility of an API instance
* Create a new connection to Salesforce and new portals
* Manage users
* Use Experience Builder to customize portal |
API Experience Hub Portal Administrator| Currently, can manage only one API portal in the organization. 
a|
* Add and remove specific APIs from the portal
* Assign the visibility of an API instance
|Salesforce System Administrator|This profile must be assigned to the Salesforce user who performs the Salesforce linking process such as the Organization administrator in the main organization and API Experience Hub Portal Administrator.
a|
* Perform the Salesforce linking process
|===

=== Consumer Users
API Experience Hub has the following consumer user profiles:

* Guest
* Member

These are groups of users with certain permissions that you can manage using the Teams feature in Anypoint Access Management. Permissions for Guest and Member users are automatically determined by how they access an organization's portal. A user who does not log in to the portal is an anonymous user that is assigned the guest user profile with the permissions assigned to this group. A guest user can become a member by completing the registration process for the portal. Once the user's registration is approved, this user inherits the member user profile and its associated permissions. For more information about Teams in Access Management, see xref:access-management::teams.adoc[Manage User Access Using Teams].

|===
|User Profile |Description |Actions
|Guest| This user’s profile is anonymous and is not logged in the API portal. 
a|
* View public APIs that are shared with them.
* Can self-register to become a member.
* Cannot request access to APIs. 
|Member|This is a registered user who can log in to a portal.
a|
* View public APIs and other APIs that are shared with them.
* Registered using self-registration to become a member.
* Request access to APIs.| 
|===


=== Exchange Permissions
All administrators must have the Exchange Viewer permission to import APIs into the portal.

|===
|Permission |Description |Actions
|Exchange Viewers|Assign this permission to the Organization Administrator or the API Experience Hub Administrator who performs the Salesforce linking process. Users with this permission cannot add new assets, edit asset portal content, or share an asset with another user.
a|
* View APIs in Exchange
* Import APIs from Exchange to the portal |
|===

== 

== Before You Begin
Consider which user in your organization you want to perform the administrator tasks.

== Grant the API Experience Hub Administrator Permission
The Organization Administration and API Experience Hub Administrator can perform all of the functions to create a portal. Only the Organization Administrator or an existing API Experience Hub Administrator can grant a user the API Experience Hub Administrator permission. Grant this permission when you want another user in your organization to perform the Salesforce linking process, create and curate the portal, manage the portal, and manage users.

To grant the API Experience Hub Administrator permission to a user:

. Log in to Anypoint Platform using an account with the Organization Administrator permission.
. Click *Access Management*.
. Click *Users*.
. Click the username of the user that you want to add the API Experience Hub Administrator permission. 
. Select *Permissions* and click *Add Permissions*.
. From the *Select permissions to add for this user* search box, enter *API Experience Hub Amin* and select the checkbox.
. Click the blue plus icon.

//=== Grant the API Experience Hub Portal Administrator Permission 

//If there is more than one users that manages the portal, you can grant another user within your organization the API Experience Hub Portal Administrator permission.

//. From *Access Management*, click *Users*.
//. Click the username of the user that you want to add the API Experience Hub Administrator permission. 
//. Select *Permissions* and click *Add Permissions*.
//. From the *Select permissions to add for this user* search box, enter *API Experience Hub Portal Amin* and select the checkbox.
//. Click the blue plus icon.

== Grant the Exchange Viewer Permission

Administrators can only add APIs for which they have the Exchange Viewer permission. All administrators must have the Exchange Viewer permission to add APIs to the portal.

When APIs are added to the portal, all administrators are assigned automatically the Exchange Viewer permission for the APIs added in the portal. 

To grant the Exchange Viewer permission to a user:

. From *Access Management*, click *Users*.
. Click the username of the user that you want to add the Exchange Viewers permission. 
. Select *Permissions* and click *Add Permissions*.
. From the *Select permissions to add for this user* search box, enter *Exchange Viewers* and select the checkbox.
. Click the blue plus icon.

== Apply the Principle of Least Privilege for Your Salesforce Organization
To install the managed package and operate within the Salesforce organization, a user with the System Administrator profile is required. This user connects the Salesforce Experience Cloud to link the Salesforce organization with the Anypoint Platform organization. The System Administrator profile might have more permissions than necessary. For users with an existing Salesforce organization and potentially sensitive data, ensure the security of that data by following the principle of least privilege. For API Experinence Hub, you can create a permission set named AEH_Anypoint, add all the necessary permissions, and assign the permission set to the a user who performs the linking process.

=== AEH_Anypoint Permission Set


The permission set must have the following permissions:

* System
** Apex REST Services
**  API Enabled
** Assign Topics
** Author Apex
** Connect Organization to Environment Hub
** Create and Customize Dashboards
** Create and Customize List Views
** Create and Customize Reports
**  Create and Set Up Experiences
** Create Dashboard Folders
** Create Report Folders
** Create Topics
** Customize Application
** Delete Topics
**  Download AppExchange Packages
** Edit Events
**  Edit HTML Templates
** Edit My Dashboards
**  Edit My Reports
**  Edit Tasks
**  Edit Topics
**  Manage Auth. Providers
** Manage Connected Apps
** Manage Custom Permissions
**  Manage Dashboards in Public Folders
** Manage Letterheads
** Manage Multi-Factor Authentication in User Interface
** Manage Public Classic Email Templates
** Manage Public Documents
** Manage Public List Views
** Manage Reports in Public Folders
**  Manage Session Permission Set Activations
** Modify All Data
**  Modify Metadata Through Metadata API Functions
**  Run Reports
** Transfer Record
** View All Data
** View Dashboards in Public Folders
** View Event Log Files
** View Login Forensics Events
** View Real-Time Event Monitoring Data
** View Reports in Public Folders
** View Roles and Role Hierarchy
** View Setup and Configuration

* User
** Assign Permission Sets
** Manage Internal Users
** Manage IP Addresses
** Manage Login Access Policies
** Manage Password Policies
** Manage Profiles and Permission Sets
** Manage Roles
** Manage Sharing
** Manage Users
** Reset User Passwords and Unlock Users
** View All Users






== See Also

* xref:connecting-to-salesforce.adoc[Connecting to Salesforce]