= Connecting to Salesforce 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

API Experience Hub is composed of a Salesforce organization with Experience Cloud and a managed package that is installed in this organization. The managed package contains the components and data objects that interact with your Anypoint Platform organization.

A connection with Salesforce Experience Cloud is required for linking to the Salesforce organization to create an API portal within Anypoint. 

IMPORTANT: Please ensure that you are linking your Anypoint organization to the correct Salesforce organization. 
//Currently, this connection can only be done once. Once the connection is made, you cannot unlink from that Salesforce organization. //

An instance of API Experience Hub connects to only one Anypoint Platform organization and Salesforce organization.

The package is installed in a sandbox or production organization. The changes made to this organization do not propagate to any other Salesforce organizations that your company might already have. The data regarding API Experience Hub in Salesforce is isolated from your company's operational data, such as ERP or CRM data.


== Before You Begin

Before you can create your portal, you must have:

* Familiarity with Anypoint Platform and Exchange, including the permissions to use 
* Anypoint Platform Organization
* API Experience Hub Admin permission
* Organizational administrator with permissions in AnyPoint
* Exchange Viewer permission

For more information about the required permissions, see xref:prerequisites.adoc[Prerequisites].

== Connect, Link, and Install 
The process of creating your API portal includes connecting with Salesforce Experience Cloud to link your Anypoint organization to your Salesforce organization, then installing the Salesforce Experience Cloud package. Currently, the linking process is a one-time step when creating your portal.

NOTE: Only an Organizational Administrator or API Experience Hub Administrator can perform the Salesforce linking.

Follow these steps to link your API portal:

. Navigate to Anypoint Platform, enter your username and password, and then click *Sign in*.
. From Anypoint Platform, select *API Experience Hub* from the list of products.
. From the *Connect to Salesforce Experience Cloud* dialog, select an option from the *Environment* list.
. If you have a custom Salesforce domain, check *I have a custom Salesforce domain* and enter your domain address.
. Click *Connect*.
. Enter your Salesforce username and password and click *Log In*. 
. Click *Allow* for MuleSoft to access your data.
. Confirm the Salesforce access information.
. Click *Continue*.
+
The process of installing the Salesforce Experience Cloud package begins. When the package is installed successfully, you receive an email.

== Next Steps
When the linking is complete, you can xref:styling-your-api-portal.adoc[style your API portal].

