= Connecting to Salesforce 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

API Experience Hub has a Salesforce organization with Experience Cloud and a managed package. The managed package is installed during the onboarding process when the API Experience Hub administrator, System Administrator, or a user with the xref:user-roles-permissions-and-profiles.adoc[AEH_Anypoint permission set] connects their Salesforce organization to the Anypoint Platform organization. The managed package contains the components and data objects that interact with your Anypoint Platform organization. The Salesforce System Administrator can view the *API Experience Hub* package in their Salesforce organization from Salesforce by navigating to *Setup* > *Installed Packages* and selecting the *API Experience Hub Package*.

A connection with Salesforce Experience Cloud is required for linking to the Salesforce organization to create an API portal within Anypoint Platform. This process must be completed only once to create a portal. Currently, an instance of API Experience Hub can connect only to one Anypoint Platform organization and one Salesforce organization.

== Connected App
API Experience Hub uses a connected app to obtain a session token in Anypoint Platform and interacts with Salesforce APIs. 

To view the connected app that is created in the Salesforce organization:

. From Salesforce, click *Setup*.
. In the *Quick Find* box, enter *app management*  and click *App Manager*.
+
The connected App (Anypoint_AEH) is listed in the table.

In this release, IP restrictions for the connected app are not supported. The connected app bypasses any trusted IP ranges in your organization. Do not change this option because it produces errors when creating the portal. For more information, see xref:troubleshooting.adoc[Troubleshooting].

== Allow Access
To complete the connection process, allow API Experience Hub to access the following:

* Access the identity URL service
* Manage user data via Web browsers
* Manage user data via APIs
* Perform requests at any time

== Admin Teams 
An API Experience Hub Admin team and an API Experience Hub Portal Admin team is created during the connecting and linking process. Once your Salesforce organization is successfully connected to your Anypoint Platform organization, the AEH Admin team is created. After the Salesforce linking process is complete, any user, who is assigned the AEH Admin, is automatically added to the AEH Admin team. 

After your styling changes for the portal are saved, the AEH Portal Admin team is created. Although the API Experience Hub Portal Administrator team is visible in Access Management, this permission is not supported in this release.

== Before You Begin Connecting to Salesforce

* Read the instructions in xref:before-you-begin-with-api-experience-hub.adoc[].
* Ensure that you are a System Admin or have the AEH_Anypoint permission set in the Salesforce organization that you are connecting with.

== Connect to Salesforce 
The process of creating your API portal includes connecting with Salesforce Experience Cloud to link your Anypoint Platform organization to your Salesforce organization, then installing the Salesforce Experience Cloud package. The linking process is a one-time step when creating your portal.

NOTE: Only an Organization Administrator, API Experience Hub Administrator, and a Salesforce user with the System Administrator profile or AEH_Anypoint permission set can link organizations.

Follow these steps to link your API portal:

. Navigate to Anypoint Platform, enter your username and password, and then click *Sign in*.
. From Anypoint Platform, select *API Experience Hub* from the list of products.
. From the *Connect to Salesforce Experience Cloud* dialog, select an option from the *Environment* list:
+
* Production
+
* Sandbox
+
If you do not know which Salesforce organization environment type you have, contact your Salesforce administrator.
. If you have a custom Salesforce domain, select *I have a custom Salesforce domain* and enter your domain address.
+
If you don't use a custom domain and you have active Salesforce sessions in the selected environment, you log in to Salesforce using the first active session.
. Click *Connect*.
. Confirm the Salesforce access information and click *Continue*.
. Click *Allow* for MuleSoft to access your data and click *Connect*..
+
//placeholder for allow access screen capture
. Click *Continue*.
+
The process of installing the Salesforce Experience Cloud package begins. When the package is installed successfully, you receive an email.

== Next Steps
When the linking is complete, you can xref:styling-your-api-portal.adoc[style your API portal].

== See Also

* xref:user-roles-permissions-and-profiles.adoc[]
* xref:assigning-permissions.adoc[]
* xref:troubleshooting.adoc[]

