= Connecting to Salesforce 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

API Experience Hub is composed of a Salesforce organization with Experience Cloud and a managed package that is installed in this organization. The managed package contains the components and data objects that interact with your Anypoint Platform organization.

A connection with Salesforce Experience Cloud is required for linking to the Salesforce organization to create an API portal within Anypoint. This process must be completed only once to create a portal. 

IMPORTANT: Please ensure that you are linking your Anypoint organization to the correct Salesforce organization. 

An instance of API Experience Hub connects to only one Anypoint Platform organization and Salesforce organization.

== Connected App
API Experience Hub uses a connected App to obtain a session token in Anypoint and interacts with Salesforce APIs. 

To view the connected App that is created in the Salesforce organization:

. From Salesforce, click *Setup*.
. Enter *app management* in the *Quick Find* box and click *App Manager*.
+
The connected App (Anypoint_AEH) is listed in the table.

In this release, IP restrictions for the connected app are not supported. If you have trusted IP ranges in your organization, they are bypassed by the connected app. We do not recommend changing this option because it produces errors when creating the portal. For more information, see xref:troubleshooting.adoc[Troubleshooting].

== Allow Access
To complete the connection process, you must allow API Experience Hub to access the following:

* Access the identity URL service
* Manage user data via Web browsers
* Manage user data via APIs
* Perform requests at any time

== Admin Teams 
An API Experience Hub Admin team and an API Experience Hub Portal Admin team is created during the connecting and linking process. Once your Salesforce organization is successfully connected to your Anypoint organization, the AEH Admin team is created. After the Salesforce linking process is complete, any user, who is assigned the AEH Admin, is automatically added to the AEH Admin team. 

Once your styling changes for the portal are saved, the AEH Portal Admin team is created. Although the API Experience Hub Portal Administrator team is visible in Access Management, this permission is not supported in this release.

== Before You Begin

Ensure that you have read the instructions in xref:prerequisites.adoc[Prerequisites].

== Connect, Link, and Install 
The process of creating your API portal includes connecting with Salesforce Experience Cloud to link your Anypoint organization to your Salesforce organization, then installing the Salesforce Experience Cloud package. The linking process is a one-time step when creating your portal.

NOTE: Only an Organization Administrator or API Experience Hub Administrator can perform the Salesforce linking.

Follow these steps to link your API portal:

. Navigate to Anypoint Platform, enter your username and password, and then click *Sign in*.
. From Anypoint Platform, select *API Experience Hub* from the list of products.
. From the *Connect to Salesforce Experience Cloud* dialog, select an option from the *Environment* list:
+
* Production
+
* Sandbox
+
If you do not know which Salesforce organization type you have,  contact your salesforce administrator.
. If you have a custom Salesforce domain, check *I have a custom Salesforce domain* and enter your domain address.
+
If you do not use the custom domain and you have active sessions with Salesforce in the selected environment, the first active session is used to log in.
. Click *Connect*.
. Confirm the Salesforce access information and click *Continue*.
. Click *Allow* for MuleSoft to access your data.
+
//placeholder for allow access screen capture
. Click *Connect*.
. Click *Continue*.
+
The process of installing the Salesforce Experience Cloud package begins. When the package is installed successfully, you receive an email.

== Next Steps
When the linking is complete, you can xref:styling-your-api-portal.adoc[style your API portal].

== See Also

* xref:troubleshooting.adoc[Troubleshooting]

