= Connecting to Salesforce 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

API Experience Hub contains a Salesforce organization with Experience Cloud and a managed package. The managed package is installed during the onboarding process. The API Experience Hub administrator or a Salesforce user with the System Administrator profile or xref:user-roles-permissions-and-profiles.adoc[AEH_Anypoint permission set] connects the Salesforce organization to the Anypoint Platform organization. The managed package contains the components and data objects that interact with your Anypoint Platform organization. The Salesforce System Administrator can view the *API Experience Hub* package in the Salesforce organization from Salesforce by navigating to *Setup* > *Installed Packages* and selecting the *API Experience Hub Package*.

A connection with Salesforce Experience Cloud is required for linking to the Salesforce organization to create an API portal within Anypoint Platform. This process must be completed only once to create a portal. Currently, an instance of API Experience Hub can connect only to one Anypoint Platform organization and one Salesforce organization.

== Connected App
API Experience Hub uses a connected app to obtain a session token in Anypoint Platform and interacts with Salesforce APIs. 

To view the connected app that is created in the Salesforce organization:

. From Salesforce, click *Setup*.
. In the *Quick Find* box, enter *app management*  and click *App Manager*.
+
The connected App (Anypoint_AEH) is listed in the table.

In this release, IP restrictions for the connected app are not supported. The connected app bypasses any trusted IP ranges in your organization. Do not change this option because it produces errors when creating the portal. For more information, see xref:troubleshooting.adoc[Troubleshooting].

== Allow Access
To complete the connection process, allow API Experience Hub to access the following:

* Access the identity URL service
* Manage user data via Web browsers
* Manage user data via APIs
* Perform requests at any time

== Admin Teams 
An API Experience Hub Admin team and an API Experience Hub Portal Admin team is created during the connecting and linking process. Once your Salesforce organization is successfully connected to your Anypoint Platform organization, the AEH Admin team is created. After the Salesforce linking process is complete, any user, who is assigned the AEH Admin, is automatically added to the AEH Admin team. 

After your styling changes for the portal are saved, the AEH Portal Admin team is created. Although the API Experience Hub Portal Administrator team is visible in Access Management, this permission is not supported in this release.


== Before You Begin Connecting to Salesforce

* Read the instructions in xref:getting-started-with-api-experience-hub.adoc[].
* Ensure that you are a System Administrator or have the AEH_Anypoint permission set in the Salesforce organization that you are connecting with.

== Connect to Salesforce  

The connecting process is a one-time step when creating your portal.

NOTE: Only an Organization Administrator, API Experience Hub Administrator, or a Salesforce user with the System Administrator profile or AEH_Anypoint permission set can connect to Salesforce to link organizations.

Follow these steps to connect to your Salesforce organization:

. Navigate to Anypoint Platform, enter your username and password, and then click *Sign in*.
. From Anypoint Platform, select *API Experience Hub* from the list of products.
. From the *Welcome to API Expea-sandbox-featurerience Hub* page, if this is the first time connecting to Salesforce, click *Let's Start*.
. Click *Connect to Salesforce*.
. To a create a portal directly in production, select *Production* from the *Environment* list.
. To a create a portal in a sandbox, select *Sandbox* from the *Environment* list.
. Enter the username and password of your Salesforce organization and click *Log In*.
. If you have a custom Salesforce domain, select *I have a custom Salesforce domain* and enter your domain address.
+
If you don't use a custom domain and you have active Salesforce sessions in the selected environment, you log in to Salesforce using the first active session.
. Click *Connect*.
. Click *Allow* for MuleSoft to access your data.
. To go back and connect to a different Salesforce organization, click *Connect with another Salesforce organization*.
+
The process of connecting to a Salesforce organization restarts.
. Confirm the Salesforce access information and click *Confirm connection*.
+
The process of connecting to Salesforce and installing the Salesforce Experience Cloud package begins. When the package is installed successfully, you receive an email.

== Next Steps
When the connection to the Salesforce organization is complete, set up the portal. For more information, see xref:setting-up-the-api-portal.adoc[].


== See Also

* xref:user-roles-permissions-and-profiles.adoc[]
* xref:assigning-permissions.adoc[]
* xref:troubleshooting.adoc[]

