= Disconnecting the Portal
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint can only be linked to one Salesforce organization; only one API portal can be created for that organization. Portal administrators can disconnect a portal when a portal is no longer needed or when you want to create a new portal with the same Salesforce organization portal.

Disconnecting your API portal removes artifacts from the API Experience Hub database and unlinks Anypoint to your Salesforce organization so that you can create another API portal.

To create a new API portal, you must disconnect the current API portal from your Salesforce organization. This process unlinks Anypoint to your Salesforce organization. You can then link your Anypoint account to a new Salesforce organization. 

To disconnect your API portal:

. From the *Manage your API portal* page, click *Settings*.
. Click *Disconnect Salesforce Org*.
. To disconnect, click *Disconnect Salesforce Org* from the message.
+
The API portal is disconnected from the Salesforce organization and no longer accessible by users. The APIs remain available in Exchange. 

== See Also

* xref:connecting-to-salesforce.adoc[Connecting to Salesforce]