= Enabling Single Sign-On for Your Portal 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Administrators or security teams can implement an external identity provider (IdP) as a login option for an API Experience Hub portal. Single sign-on (SSO) authentication provides a seamless login experience for your customers with your organization’s unique branding. Your users can log in to your portal without having to remember another username and password or entering login credentials multiple times. 

When a member of your portal visits the portal page and selects the SSO option, they are redirected to the identity provider login page to authenticate. The SSO authentication process uses the identity provider to check the identity of a user. If the login is successful, the user is created in Access Management that aligns with the user profile. The API Experience Hub portal home page displays for the user to browse and discover APIs.

Access Management configures identity management for SSO for Anypoint. For more information about identity providers, see Identity Management in Access Management.

== User Roles
Setting up an identity provider for API Experience Hub includes multiple personas that perform different user actions. 

Depending on your organization’s setup, a user may be assigned one or more of the following roles:

* API Experience Hub Administrator  
+
The AEH Admin is responsible for enabling and disabling an identity provider in the API EXperience Hub UI.
Salesforce System Administrator
The Salesforce System Administrator is responsible for setting up the identity provider in Salesforce.
* Anypoint Organization Administrator
+
The Anypoint Organization Administrator is responsible for mapping the identity provider groups with the API Experience Hub profiles using the group mapping functionality of Access Management teams.
* Security team
+
Your organization’s security team is responsible for setting up the identity provider with the required user-groups and applications. 

Your organization’s Security team and the Salesforce System Administrator, who manage the identity provider system in an organization, configure the proper login option in Salesforce. The Security team and the Org Admin in the main organization may want to configure the same identity provider option in Anypoint, if required. The Security team and the Org Admin in the main organization configures the mapping between Salesforce and Anypoint. Access Management provides the functionality of adding group mappings for external identity providers using teams. When the group mappings are properly configured, users who log in to the portal are added automatically to the out-of-the-box profile that they belongs to. The default identity provider is provided to create identities in Anypoint for Salesforce users.

Anypoint and Salesforce can configure an identity provider using OpenID Connect (auth provider) or SAML (Single Sign-on Settings). 

== Out-of-the-Box Solutions
API Experience Hub provides the following out-of-the-box solutions for enabling SSO:

* anypoint_idp_id
+*
The custom claim or SAML attribute provides the information that is received from the identity provider that determines which Anypoint identity provider a user should be mapped to.

* AEH Users - ${salesforceOrganizationId}
+
The default identity provider that's created in Anypoint to map all self-registered users. This identity provider is used when the aeh_portal_idp is not set in the identity provider. Self-registered users are mapped with the default identity provider.

* AEH Portal - ${salesforceOrganizationId}_${salesforceCommunityId} 
+
This solution creates a team called AEH Portal in Access Management automatically. This team includes administrators, guests, and members profiles. You select this team when adding the group mapping. For more information, see *Add Group Mappings*.

* AEHPortalRegistrationHandler.cls 
+
A single Apex class is provided in the API Experience Hub package called AEHPortalRegistrationHandler.cls that is compatible with SAML and OpenID Connect.  
+* 
The registration handler is a piece of Apex code that runs when a user logs in to the Salesforce Experience Cloud site. When the identity provider is configured properly, Salesforce passes the portal ID to the AEHPortalRegistrationHandler. If the user does not exist, the registration handler creates the user entity in Salesforce. If the user exists, the handler updates the user metadata based on information sent by the identity provider, for example, the user’s first name and last name. The registration handler must be contextualized with the portal ID in Salesforce to load specific configurations by the portal. For example, the user gets created in the profile and account related to the portal from the NetworkSelfRegistration object. 

You select this handler when configuring an authentication provider for Salesforce. See *Configure an Authentication Provider* for more information about setting this registration handler.

== Basic Terminology

The following terms are referenced in this topic:

*Authentication Provider*

An authentication provider is a framework that allows you to connect Salesforce to a third party for authorized data access, authentication, or both, depending on the protocol. Authentication providers can implement OAuth 2.0 to authorize Salesforce to access third-party data. Or they can implement OpenID Connect or custom authentication protocols to support both third-party data access and authentication.

When you're using authentication providers, Salesforce is always the relying party. If the authentication provider implements OpenID Connect, we refer to the third party as the OpenID provider. If it implements a custom authentication protocol, we call the third party the identity provider.

*Identity Provider*

An identity provider acts as a trusted service that authenticates a user’s identity.

*OpenID Connect*

OpenID Connect is an open standard authentication protocol built on top of OAuth 2.0. With OpenID Connect, the relying party and OpenID provider can exchange information about who a user is and what they can do with a service.

*OpenID Provider*

In OpenID Connect, an identity provider is called an OpenID provider. It authenticates users as requested by the relying party.

*Relying Party*

In OpenID Connect and custom authentication protocols, a service provider is called a relying party, though some use the terms interchangeably. It relies on the OpenID provider or identity provider for authentication.

*SAML* 

*Single Sign-On*

Single sign-on (SSO) is an authentication method that enables users to access multiple applications with one login and one set of credentials. For example, after users log in to your org, they can automatically access all apps from the App Launcher. You can set up your Salesforce  or Anypoint org to trust a third-party identity provider to authenticate users. Or you can configure a third-party app to rely on your org for authentication.

== Before You Begin
Before enabling SSO, ensure you have the following permissions:

* * The Organization Administrator permission or role in the main Anypoint organization.
The System Administrator role in Salesforce.

== Set Up SSO 

Setting up SSO for your portal includes the following high-level steps. These steps can vary depending on your use case. 

//TODO: user journey flow diagram here - should be the minimal steps 

Performing steps require you to move back and forth between the application and the identity provider application to copy or add information.

Step 1: Enable SSO for Your Portal

In this step, you create and set up an application in the identity provider. 

Step 2: Add Salesforce Identity Providers 

In this step, you add the Salesforce identity provider from API Experience Hub UI using the Login settings tab on the User Management page. From the Login settings tab, you enable SSO for the identity provider. Once the identity provider is enabled, users can see the login option from the portal’s login page.

Step 3: Add Group Mappings

In this step, you map the groups created in the Salesforce identity provider that you added to the corresponding team profile for the portal.

Step 4: Test the SSO Configuration

In this step, you test the SSO configuration that you just set up for the portal.

Step 1: Enable SSO for Your Portal
To enable SSO, an identity provider is required for Anypoint to create identities in Anypoint for Salesforce users. 

=== Username Assignment Strategy
If you want to set up an SSO login option for your portal and your Anypoint and Salesforce organizations have identity providers already configured, review the username assignment strategy for your identity providers since they may be different. To have a single identity between Anypoint and Salesforce, the format for the username assignment must be the same. For Anypoint, you can use any character string however, Salesforce has a specific username strategy that uses an email format. If the username strategy does not match, extra attributes within the user profile must be added to the profile editor of the identity provider. Then, this information must be mapped with the Anypoint identity provider that you are using for SSO.

Consider the following use cases when determining the username assignment for your users.

*Use Case 1* 

You want to configure an identity provider as a login option for your portal. If there is no identity provider configured in Anypoint, you don’t need to map the identity provider for the portal to the identity provider in Anypoint since the default identity provider can be used for the portal. Every Salesforce user will also have an identity in Anypoint.
 
*Use Case 2* 

You want to configure an identity provider as a login option for your portal. An identity provider is already configured in your Salesforce and Anypoint organizations and the usernames in both organizations match in each identity provider. For example, the Salesforce and Anypoint username is *anyuser@salesforce.com*. No extra steps to reconcile the usernames are necessary.

*Use Case 3*

You want to configure an identity provider as a login option for your portal. An identity provider is already configured in your Salesforce and Anypoint organizations and the username used in those organizations do not match. For example, the Salesforce username is *anyuser@salesforce.com* and the Anypoint username is *anyuser*. To have a single user identity, you must reconcile the username format by adding attributes for *anypoint_idp_id* and *anypoint_username*.

Configure an identity provider as a login option for the API Experience Hub portal using the following steps. 

=== Create and Set Up an Application for the Portal in the Identity Provider
In this step, you create an application in the identity provider for the API Experience Hub portal, enable the ability to send group information in the application configuration, configure groups, and configure the default identity provider. 

. Create a new application for the API Experience Hub portal in the identity provider using OpenID Connect or SAML.
+
NOTE: You can add the redirect URIs in the application after you configure the identity provider in Salesforce in a later step.
. Configure a custom OpenID Connect groups claim filter or a SAML attribute called groups. This value contains all of the groups that the user belongs to.
+
For example, in Okta, you can choose to use a Groups claim filter using *regex .** to match all groups.



. Add a username assignment strategy for the user.
+
For example, in Okta, you can click *Assignments* and enter the *Username* using one of the following examples:

* Use *user.login* when the Anypoint username is the same as the identity provider username. 
+
* Use *String.substringBefore(user.login, "@")* to remove the email domain since Okta usernames are email-based.
* If Anypoint and Salesforce have identity providers already configured and the username assignments are the same, there is nothing to do.
+
* If Anypoint and Salesforce have identity providers already configured and the username assignment format does not match, reconcile the format by adding attributes for *anypoint_idp_id* and *anypoint_username*. The following instructions are using Okta as the identity provider. For all other identity providers, see the identity provider’s documentation for more information.
+
.. From Okta, click *Directory* > *Profile Editor* for the identity provider and select the recently created application.
.. Click *Add Attribute*.
.. From *Data Type*, select string.
.. From *Display name*, enter *anypoint_idp_id*.
.. From *Variable name*, enter *anypoint_idp_id*.
.. From *Attribute length*, select *Between*.
.. From *User permission*, select *Read Only*.
.. Click *Add*.
.. Repeat steps 1 through 8 to add an attribute for anypoint_username and enter *anypoint_username* for the *Display name* and the *Variable name*.
.. Click *Save*.
. If you want to map the portal identity provider to an existing identity in Anypoint, configure a custom claim or SAML attribute called *anypoint_idp_id* and force an update on existing identity provider users to match the identity in the portal to the users in Anypoint. 
+
NOTE: If the user already exists and logs in to the portal before the *anypoint_idp_id* is set, the default identity provider *AEH Users - ${salesforceOrganizationId}* is used. The user is not added to the new identity provider specified in the anypoint_idp_id field to prevent the user from being duplicated.
+
Here is an example of what it looks like in Okta:

. If you want to assign users to a specific identity provider and not the default Anypoint identity provider, follow these steps:
.. Go to *Access Management* > *Identity Providers*. 
.. Click the identity provider of your choice and copy and paste the 32 digit ID in the URL in the custom claim or SAML attribute called anypoint_idp_id that’s configured in the identity provider.
+
You can also copy the 32 digit ID from the *Assertion Consumer Service (ACS) URL* field :




== See Also

* xref:troubleshoot-sso-errors.adoc[Troubleshoot Single Sign-On Errors]
* xref:managing_users.adoc[Managing Users]



