= Getting Started with the Pilot Release
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The primary design of API Experience Hub is reducing the complexity of Salesforce configuration and providing simple API portal creation. API Experience Hub has a more modern, reliable, and flexible portal experience that is achieved through the migration of Salesforce Lightning Web Components. The API console is redesigned to be more intuitive for developers, product managers, and other roles for the exploration and consumption of APIs. Moving the major administrative tasks and user management directly onto Anypoint makes it easier for administrators to manage their portals.

The goals of this pilot are to establish product market fit for API Experience Hub, engage with the field and customer success group on the product, and identify high-priority bugs before the release at the end of March 2023 (FY24). Participants in the pilot can expect a streamlined setup experience and a first review of the enhanced look and feel of the portal. You can set up the portal, onboard APIs on it, and view the consumption experience for developers on the API carousel, catalog, and console.

For the purpose of this pilot, the following users can perform these tasks: 

*Portal administrators*:

* link:deploying-your-portal.adoc[Deploy API Portal]
* link:creating-your-api-portal.adoc[Create an API Portal]
* link:administering-your-portal.adoc[Enable Self-Registration]
* link:managing-your-portal#add-apis-from-exchange[Add APIs from Exchange] 
* link:managing-your-portal#remove-apis-from-the-portal[Remove APIs from the Portal]
* link:managing-your-portal#make-api-versions-visible[Make API Versions Visible]
* link:customizing-your-portal.adoc[Customize the API portal] Using Experience Builder
* link:publish-your-portal.adoc[Publish the API Portal] Using Experience Builder
* link:deactivate-your-portal-site.adoc[Deactivate Your Portal Site]

*Developers*:

* link:access-an-api-portal.adoc[Self-Register and Access the API Portal]
* link:search-for-apis.adoc[Search for APIs]
* link:view-api-details.adoc[View API Details Page]
* link:download-an-api-specification.adoc[Download API Specification]
* link:api-console-specification-and-documentation.adoc[Inspect API Console Specification and Documentation]

== See Also

* link:default-settings.adoc[Default Settings]
* link:limitations.adoc[Limitations]





