= Getting Started with the Pilot Release
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The primary design of API Experience Hub is reducing the complexity of Salesforce configuration and providing simple API portal creation. API Experience Hub has a more modern, reliable, and flexible portal experience that is achieved through the migration of Salesforce Lightning Web Components. The API console is redesigned to be more intuitive for developers, product managers, and other roles for the exploration and consumption of APIs. Moving the major administrative tasks and user management directly onto Anypoint makes it easier for administrators to manage their portals.

The goals of this pilot are to establish product market fit for API Experience Hub, engage with the field and customer success group on the product, and identify high-priority bugs before the release at the end of March 2023 (FY24). Participants in the pilot can expect a streamlined setup experience and a first review of the enhanced look and feel of the portal. You can set up the portal, onboard APIs on it, and view the consumption experience for developers on the API carousel, catalog, and console.

For the purpose of this pilot, the following users can perform these tasks: 

Portal administrators:

* Deploy API Portal
* Create an API Portal
* Enable Self-Registration
* Add APIs from Exchange and Manage APIs in the Portal 
* Make API Versions Available
* Customize the API portal Using Experience Builder
* Publish the API Portal Using Experience Builder
* Deactivate Your Portal Site

Developers:

* [Self-register and access the API portal]
* Search for APIs
* View API Details Page
* Download API Specification
* Inspect API Console Specification and Documentation

== Default Settings
The following settings are set by default when the portal is created:

* Guest User Access is enabled
* Portal status is active 
* Portal site is live and published 
+ 
To make the site unaccessible, see link:deactivate-your-portal-site.adoc[Deactivate Your Portal Site] for more information
* Five APIs are automatically added to the API carousel in the Home page, API catalog in the APIs page, and in the APIs in the portal tab of API Management. 
+
These APIs are the latest created APIs in Exchange. The default visibility for the APIs is Administrator only. The administrator of the portal can change this visibility for each API in the API Management tab. These APIs can be removed. See Remove APIs from the Portal for more information.
Portal site is live upon creation
To make the site unaccessible, see Deactivate Your Portal Site for more information


For the pilot, there is no access to guest users. You can disable this access and then delete the permission set assigned to the guest user.

Use the following steps to disable guest user access:

. Open Experience Builder.
. In *Settings* > *General*, uncheck *Guest users can see and interact with the site without logging in*.
. Go to *Setup* > *Sites* and click the community label.
. From the Sites detail page, click Public Access Settings.
+
The Guest User Profile displays.
. Click *Assigned Users*.
. Click *Site Guest User*, *[Community name]*.
. Click *Permission Set Assignments*.
. Delete the *ACM Guest User Permission* set.

Once the API portal is created, it is given an active status. The portal is not live until it is published.

== Limitations
The pilot has the following limitations:

* An API portal can have a maximum of 160 APIs
* API Groups are not available
* My Applications page is not available
* Request Access option is not available
* API details cannot be modified
* API Experience Hub is not certified for use on mobile devices. Some functionality works on mobile devices, but some functionality such as the API console does not.




