= Installing 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

API Experience Hub is composed of a Salesforce organization with Experience Cloud and a managed package that is installed in this organization. The managed package contains the components and data objects that interact with your Anypoint Platform organization.

An instance of API Experience Hub connects to only one Anypoint Platform organization. The Anypoint user can connect to one or more instances of API Experience Hub, possibly including sandbox instances and instances in other Salesforce organizations.

The package is installed in a Salesforce organization that is independent of any other Salesforce organizations that your company might already have, so that the API portal data is isolated from your company operational data, such as ERP or CRM data.

The Salesforce organization with Experience Cloud is provisioned through and included in the API Experience Hub license from MuleSoft. You don’t need to procure this Salesforce organization separately, and you cannot reuse existing Salesforce licenses for API Experience Hub. 

== Before You Begin
Before getting started, ensure that you have:

* Familiarity with Anypoint Platform and Exchange, including    permissions to use Exchange to publish and view RAML or OAS specifications in your business group
* An Anypoint Platform account
* Administrator or Contributor permissions

== Install Salesforce Experience Cloud Package

Follow these steps to install the installation package:

. Navigate to Anypoint Platform, enter your username and password, then click *Sign in*.
. Select *API Experience Hub* from the list of products.
. Click *Connect to Salesforce Experience Cloud*.
. Select an option from *Environment*. 
. Check the *I have a custom Salesforce domain* box if you have a Salesforce domain. 
. Click *Connect*.
. Enter your Salesforce username and password, and click *Log In*.
+
This is a one-time step.
. Click an option to deny or allow MuleSoft to access your data.
+
The installation process of the Salesforce Experience Cloud package begins.


== Next Steps

When the installation is complete, click *Create your API Portal* to set up your API Portal.
