= Limitations
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This release has the following limitations:

* API Experience Hub does not use platform cache.
* API Experience Hub functions at the main organization level only.
* A Salesforce organization can't connect to more than one Anypoint organization.
* Multiple portals per Salesforce organization aren’t supported.
* An API portal can have a maximum of 350 APIs.
+
Don't make changes to the permissions of the out-of-the-box Teams created in Access Management for API Experience Hub. Each asset added to the API portal uses two permissions and Access Management has a limit of 1000 permissions per team.
* API Groups aren't available.
//* API details can't' be modified.
* API Experience Hub isn't certified for use on mobile devices. Some functionality works on mobile devices, but some functionality such as the API Console does not.
* IP restrictions aren't supported. For more information, see the xref:troubleshooting.adoc[Troubleshooting] section.
* Validation rules can't be applied to standard objects that are created during the Salesforce linking process. For more information, see the xref:troubleshooting.adoc[Troubleshooting] section for a work around.
* Existing users can't self-register. They must use an identity provider to access the portal.
* The maximum pending user registration requests is 500. For more information, see xref:managing-users.adoc[Managing Users].
* The API Experience Hub package is installed in the sandbox and production environments on the same date. As a result, you can't use your sandbox organization for testing in the development cycle.
* The community portal's default name API Experience Hub can't be changed. Changing the name of the portal generates errors in the configuration.
* You can't change the names of APIs in API Experience Hub.
