= Limitations
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This release has the following limitations:

* API Experience Hub does not use platform cache.
* API Experience Hub functions at the main organization level only.
* You cannot connect a Salesforce organization to more than one Anypoint organization.
* An API portal can have a maximum of 250 APIs.
+
Do not make changes to the permissions of the out of the box Teams created in Access Management for API Experience Hub. Each asset added to the API portal uses two permissions and Access Management has a limit of 1000 permissions per team.
* API Groups are not available.
//* API details cannot be modified.
* API Experience Hub is not certified for use on mobile devices. Some functionality works on mobile devices, but some functionality such as the API Console does not.
* IP restrictions are not supported. For more information, see the xref:troubleshooting.adoc[Troubleshooting] section.
* Validation rules cannot be applied to standard objects that are created during the Salesforce linking process. For more information, see the xref:troubleshooting.adoc[Troubleshooting] section for a work around.