= Limitations
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This release has the following limitations:

* API Experience Hub does not use platform cache.
* API Experience Hub functions at the main organization level only.
* A Salesforce organization can't connect to more than one Anypoint organization.
* Multiple portals per Salesforce organization aren’t supported.
* API Groups aren't available.
* The maximum number of user groups is 20.
* New API portals can have a maximum of 7,000 APIs.
* Existing API portals can have a maximum of 350 APIs.
+
Don't make changes to the permissions of the out-of-the-box Teams created in Access Management for API Experience Hub. Each asset added to the API portal uses two permissions and Access Management has a limit of 1,000 permissions per team.
* Enable scalability on the *API management* page to increase the maximum number of APIs to 7,000 for the API portal. After you enable this option, you can't revert to the portal version that supports up to 350 APIs.
+ 
For more information, see xref:managing-apis.adoc#opt-in-to-increase-the-number-of-apis[Opt in to Increase the Number of APIs in the Portal]. 
* API Experience Hub isn't certified for use on mobile devices. Some functionality works on mobile devices, but some functionality such as the API Console does not.
* IP restrictions aren't supported. For more information, see the xref:troubleshooting.adoc[Troubleshooting] section.
* Validation rules can't be applied to standard objects that are created during the Salesforce linking process. For more information, see the xref:troubleshooting.adoc[Troubleshooting] section for a work around.
* The maximum pending user registration requests is 500. For more information, see xref:managing-users.adoc[Managing Users].
* The community portal's default name API Experience Hub can't be changed. Changing the name of the portal generates errors in the configuration.
* You can't change the names of APIs in API Experience Hub.
* API Experience Hub Lightning custom components support English only. For more information, see xref:api-experience-hub-lightning-components.adoc[]
* Microsoft Azure OpenID Connect isn’t supported.