= Customizing the Portal Look-and-Feel  
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Builder creates a Salesforce Experience Cloud site with your desired brand identity, look and feel, and site structure by providing control over the site’s components, themes, and pages, and its settings for general properties, themes, and SEO. 

The Builder link opens your site for editing. You can edit each page in your portal, create new pages, and add and edit the components on each page.

The Builder interface contains the pages list, component palette, theme menu, page structure menu, and settings menu.

API Experience Hub isn't certified for use on mobile devices. Some functionality works on mobile devices, but some functionality such as the API Console does not.

== Pages List
The Pages list shows the pages included with API Experience Hub and the pages you have added and enables you to select and edit each page. The included page Home is selected by default.

The Pages list enables you to create new pages by using the New Page option. A new page can be an object page or a standard page. Object pages are used only with Salesforce objects, so a custom community page starts as a standard page. A standard page can start from one of the preconfigured pages or as a new blank page.

Make a new blank page by selecting the layout and then entering the new page’s name and URL. Use that URL to make links to the new page, including links in menus.
The new page displays placeholders for content based on the layout.

Fill in a new page by adding components from the Components menu, such as a Headline component in the page header, or an API Experience Hub component such as an API Version Carousel.

The Pages list shows the editable configuration properties for each page, which are described in https://help.salesforce.com/s/articleView?id=sf.community_builder_manage_pages_overview.htm&type=5[Manage Your Community’s Pages and Their Properties in Experience Builder].

== Components
Clicking the Components lightning bolt icon displays the component palette, which includes Salesforce Experience Cloud components, such as Headline or Featured Topics, and components specific to API Experience Hub, such as API Carousel or API Console. You can drag any component from the component palette to the current page. Select the component on the page to show the component’s configuration options.

API Experience Hub has the following Lightning components:

* API Console
* Asset Detail Header
* Asset Documentation Viewer
* Assets Carousel
* Assets Catalog
* Search Box
* Search Result

Detailed component information is available from the page and the Salesforce Experience Cloud https://help.salesforce.com/s/articleView?id=sf.rss_component_reference_table.htm&type=5[Components] documentation. See xref:api-experience-hub-lightning-components.adoc[API Experience Hub Lightning Components] for a description of each component.

== Theme
Clicking the Theme paintbrush icon offers these general branding parameters:

* Colors
+
Sets the site’s general color scheme, including paragraph, heading, and button text.
* Images
+
Specifies the site’s company logo and the login page’s background Image.
* Fonts
+
Specifies the site’s fonts, which include a primary font and header fonts, and specifies the site’s text case.
* Theme Settings
+
You can adjust community styling by editing the CSS rules. Next to the Theme title, click the Theme list, and click Edit CSS.
Refer to https://help.salesforce.com/s/articleView?id=sf.community_builder_theme_customize.htm&type=5[Customize Your Experience Site Theme].

Brand multiple portals using branding sets. For more information, see https://help.salesforce.com/s/articleView?id=sf.community_designer_brandsets.htm&type=5[Use Branding Sets in Experience Builder].

== Page Structure
Clicking the Page Structure icon, which resembles a bulleted list, shows the components in the current page and enables you to select and remove them. Selecting a component displays its configuration menu.

== Settings
Clicking the Settings gear icon offers these parameters:

* https://help.salesforce.com/articleView?id=community_builder_general_settings.htm&type=5[General]
* https://help.salesforce.com/articleView?id=community_builder_theme.htm&type=5[Theme]
* SEO
+
Search Engine Optimization (SEO) features define what information can be indexed by external services and discovered through online searches, and can increase traffic to your public community.

Refer to the https://help.salesforce.com/s/articleView?id=sf.community_builder_general_settings.htm&type=5[Experience Builder Settings] help topic for more information.

== See Also
xref:api-experience-hub-lightning-components.adoc[API Experience Hub Lightning Components]
