= Managing Your Portal 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

From API Management, curate your portal by viewing information about an API from Exchange,  adding or removing APIs, and changing the visibility of an API version.

API Management shows the following information:

* *APIs in the portal* 
+
Shows the APIs that have been added to your portal and includes a physical count of APIs that were added. When the portal is created, the last five APIs that were created in Exchange are added to this tab. The default visibility for the APIs is Administrators only. The administrator of the portal can change this visibility for each API in the API Management tab. These APIs can be removed. See Remove APIs from the Portal for more information.

* *APIs in Exchange*
+
Shows the APIs that exist in your Exchange organization but have not been added to your portal.

== View APIs in Exchange
You can view information about an API directly from Exchange to determine whether you want the API in your portal.

From the APIs in Exchange tab, select an API from the list, click more options, and select *View in Exchange*.

== Add APIs from Exchange
Curate your portal in API Experience Hub by adding APIs from Exchange. When adding APIs to the portal, the default visibility is Administrator only. You can change the visibility to include members or everyone. See link:make-api-versions-visible.adoc[Make API Versions Visible] for more information.


To add APIs to your portal:

. From API Management, select the *APIs in Exchange* tab.
. To search for an API by name or description, enter the name or description into the *Search* bar.
. Select an API from the list, click the more options icon, and select *Add to portal*.
+
The API displays in the list in the *APIs in the portal* tab.

== Remove APIs from the Portal
To remove APIs from your portal:

. From API Management, select the *APIs in the portal* tab.
. To search for an API by name or description, enter the name or description into the *Search* bar.
. Select an API from the list, click the more options icon, and select *Remove from portal*.
+
In the *APIs in the portal* tab, the API is removed from the list.

== Make API Versions Visible

You can determine which version of an API a user can view in your portal. You can set the visibility to Administrators only, Members only, or Everyone.

* Administrators only
+
Use this option if you want the version to be seen only by the portal administrator.
* Members only
+ 
Use this option if you want the version to be seen only by logged-in members
* Everyone
+
Use this option if you want the version to be publicly available to anyone.

If the visibility is Everyone or Members only, then consumer developers can see the new API version in the API carousel of the portal.

To edit the user visibility that displays for an API:

. From API Management, select *APIs in Portal*.
. To search for an API by name, enter the name into the *Search* field.
. Select an API from the list, click more options, and select *Edit display details*.
. To change the API version visibility, select an option from the *Visibility* drop-down list for the corresponding version.
. To save the changes, click *Save*.


== Next Steps
From API Management, you can further customize your portal using Experience Builder. To open the Builder, click *Customize in Experience Builder*.
