= Catalog Management 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

From the *Catalog management* page, curate your portal by viewing information about an asset from Exchange, adding or removing assets, and changing the visibility of a version.

The portal supports these service types:

* Agents
* AsyncAPI
* GraphQL
* gRPC
* HTTP
* LLM
* MCP server
* REST
* SOAP

The *Catalog management* page shows this information:

* *Services in the portal* 
+
Shows the services that have been added to your portal. Administrators can add only those services for which they have Exchange Viewer permission. For more information, see xref:assigning-permissions.adoc[]. 

All administrators are automatically assigned the Exchange Viewer permission for all Shows the services that have been added to your portal. Administrators can add only those services for which they have Exchange Viewer permission. For more information, see xref:assigning-permissions.adoc[]. 
services added to the portal. By default, the visibility of the services is set to Administrators. The portal administrator can change the visibility or remove services in the *Services in the portal* tab. 

* *Services in Exchange*
+
Shows the services that exist in your Exchange organization but haven't been added to your portal.

== Opt in to Increase the Number of Services in the Portal
Enable portal scalability in the *Catalog management* page. Opt in once for maximum service support in your portal. After enabling this option, you can't revert to the portal version that supports up to 350 services. New portals automatically scale to 7,000 services.

. Click *Learn more* from the sidebar in *Catalog management*.
. Select *I understand and want to enable scalability.* and click *Enable*.

== View Services in Exchange
You can view information about a service directly from Exchange to determine whether you want to add the service in your portal.

From the *Services in Exchange* tab, select a service from the list and select *View in Exchange*.

To filter services by categories and tags, select an option from the *Any category* or *Any tag* dropdown and click *Apply*.

== Add Services from Exchange
Curate your portal in API Experience Hub by adding services from Exchange. You must have Services in Exchange before you can add them to your portal. When adding services to the portal, the default visibility is Administrator. You can change the visibility to include members or everyone. See <<make-api-versions-visible,Make API Versions Visible>> for more information.

To add services to your portal:

. From the *Catalog management* page, select the *Services in Exchange* tab.
. To search for a service by name or description, enter the name or description into the *Search* bar.
. To filter services by categories and tags, select an option from the *Any category* or *Any tag* dropdown and click *Apply*.
. Locate the service in the list, click *+ (Add to portal)*.
+
The service displays in the list in the *Services in the portal* tab.

== Remove Services from the Portal
To remove services from your portal:

. From the *Catalog management* page, select the *Services in the portal* tab.
. To search for a service, enter the name, description, category, or tag keyword into the *Search* box.
. To filter services by categories and tags, select an option from the *Any category* or *Any tag* dropdown and click *Apply*.
. Locate the service in the list and click the trash can (Remove from portal).
. Click *Confirm*.
+
In the *Services in the portal* tab, the service is removed from the list.

== Make Versions Visible
By default, when you add a new service, the minor version shared with an Administrator is the latest version of the service. The instance visibility is set to Public instances. Only the instances that are public in Exchange are available for end-users to request access to them.

You can manage which version of a service a user can view in your portal. You can set the visibility to Administrators, Members and user groups, Guests, or None.

* Administrators 
+
Use this option if you want the version to be seen by the portal administrator only.
* Members 
+ 
Use this option if you want the version to be seen only by logged-in members or specific user groups.
* Guests
+
Use this option if you want the version to be publicly available to anyone.

* None
+
Select no users to hide the version from everyone.

If the visibility is Guests, Members, or user groups, consumer developers can see the new version in the carousel of the portal.

To edit the user visibility that displays for a service:

. From the *Catalog management* page, select *Services in the portal*.
. To search for a service, enter the name, description, category, or tag keyword into the *Search* box.
. To filter services by categories and tags, select an option from the *Any category* or *Any tag* dropdown and click *Apply*.
. Locate the service in the list and click *Edit visibility*.
. Select an instance visibility option:
+
* All instances - End-users can't request access.
* Public instances - End-users can request access. 
. Expand an API version and select the users who can see the service.
. Click *Save*.

== Next Steps
From xref:managing-users.adoc[User Management], you can view and manage users and access requests from guest users.


