=  Working With Sandboxes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Use Salesforce sandbox organizations to test your portal in a sandbox environment under the same conditions as your production environment. API Experience Hub enables you to manage separate deployment environments for your API portal. You can connect to multiple Salesforce sandbox organizations and switch between them. Manage Salesforce organizations from the *Manage your API portal* page by selecting sandbox environments that are available in the current Salesforce connection.  


//screen capture of org switcher

== Before You Begin
Ensure that you have sandbox organizations already set up. For more information about creating sandboxes, see https://help.salesforce.com/s/articleView?id=sf.data_sandbox_create.htm&type=5[Create a Sandbox] in the Salesforce documentation.

== Manage Salesforce Organizations 

. In the *Manage your API portal* page, click the organization switch control. 
//screen capture of environment/sandbox switcher control
. To connect to a production organization, click *Connect production org* from the *Connected Salesforce Orgs* dialog.
. To switch to another a sandbox for the connected production organization, click *Switch to this org* from the *Connected Salesforce Orgs* dialog.
. To connect to a sandbox organization that is not connected, click *Connect*.
. To connect to a new sandbox organization, click *Connect new sandbox org*.
. To switch to another sandbox organization, click *Switch to this org*.

== Manage Orphaned Sandboxes
Orphan sandboxes occur when the connection to the production organization is disconnected and there are child sandbox organizations still connected. If you connected to a sandbox that is not a child of the production organization, the sandbox appears as an orphan.

== Manage Refreshed Sandbox Connections
Refreshing a sandbox updates its metadata from the source organization.

== Delete Sandbox Organizations 

To delete a sandbox organizaton, see https://help.salesforce.com/s/articleView?id=000383260&type=1[Delete a sandbox] from the Salesforce documentation.

== Promoting a Sandbox to Production
When a portal is tested in a sandbox environment and is ready for production, deploy a subset of the Salesforce metadata using your CI/CD pipeline to production. Afterward, connect to the production instance with the subset of the Salesforce metadata to complete the installation and start curating APIs.

=== Before You Begin
Ensure you have basic knowledge of the following:

* Version control systems (VCS) like Git 
* https://developer.salesforce.com/tools/salesforcecli[Salesforce CLI]  
* CI/CD pipeline concepts

=== Promote a Sandbox to Production

. Configure API Experience Hub in the Sandbox organization:
.. Navigate to Anypoint Platform, enter your username and password, and then click *Sign in*.
.. From Anypoint Platform, select *API Experience Hub* from the list of products.
.. Create a portal.
.. Add assets to the portal.
.. Preview your portal and add more customizations using Experience Builder.
.. Publish your portal and test it.
+
The next step is moving all of the portal's styling and customizations from the sandbox organization to the production Org, or another sandbox organization if you want to test the process.
. Create a Git repository to store the API Experience Hub metadata:
.. https://docs.github.com/en/repositories/creating-and-managing-repositories/quickstart-for-repositories[Create a Git repository]. 
.. Clone it locally to your machine. 
.. https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_create_new.htm[Create a SFDX project].
.. Create a manifest package.xml in *./config*, for example:
+
[codeblock]
----
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
   <types>
       <members>homeroCompanyLogo</members>
       <members>homeroLoginBackground</members>
       <members>minionHomeBanner</members>
       <members>minionPageBanner</members>
       <name>ContentAsset</name>
   </types>
   <types>
       <members>API_Experience_Hub1_banner</members>
       <members>API_Experience_Hub1_logo</members>
       <name>StaticResource</name>
   </types>
   <types>
       <members>AEH</members>
       <members>AEH/API_Experience_Hub1_logo</members>
       <name>Document</name>
   </types>
   <types>
       <members>AEH</members>
       <members>AEH/ChangedPasswordEmailTemplate</members>
       <members>AEH/ForgotPasswordEmailTemplate</members>
       <members>AEH/NewMemberWelcomeEmailTemplate</members>
       <members>AEH/RejectedMemberEmailTemplate</members>
       <name>EmailTemplate</name>
   </types>
   <types>
       <members>AEHLetterhead</members>
       <name>Letterhead</name>
   </types>
   <types>
       <members>Anypoint</members>
       <members>AnypointDevx</members>
       <members>AnypointEu</members>
       <members>AnypointQax</members>
       <members>AnypointStgx</members>
       <members>ExchangeAssetIcons</members>
       <members>ExchangeAssetIconsDevx</members>
       <members>ExchangeAssetIconsEu</members>
       <members>ExchangeAssetIconsQax</members>
       <members>ExchangeAssetIconsStgx</members>
       <members>GStaticFonts</members>
       <members>GoogleFonts</members>
       <members>SegmentAPI</members>
       <members>SegmentCDN</members>
       <name>CspTrustedSite</name>
   </types>
   <types>
       <members>Anypoint</members>
       <members>AnypointDevx</members>
       <members>AnypointEu</members>
       <members>AnypointQax</members>
       <members>AnypointStgx</members>
       <members>ExchangeAssetIcons</members>
       <members>ExchangeAssetIconsDevx</members>
       <members>ExchangeAssetIconsEu</members>
       <members>ExchangeAssetIconsQax</members>
       <members>ExchangeAssetIconsStgx</members>
       <members>SegmentAPI</members>
       <name>RemoteSiteSetting</name>
   </types>
   <!--
   <types>
       <members>ExperienceBundle</members>
       <members>Communities</members>
       <name>Settings</name>
   </types>
   -->
   <types>
       <members>API_Experience_Hub_Manage_Networks</members>
       <name>PermissionSet</name>
   </types>
   <types>
       <members>API Experience Hub</members>
       <name>Network</name>
   </types>
   <types>
       <members>HTTP_API_Audience</members>
       <name>Audience</name>
   </types>
   <types>
       <members>API_Experience_Hub</members>
       <name>CustomSite</name>
   </types>
   <types>
       <members>API_Experience_Hub1</members>
       <name>ExperienceBundle</name>
   </types>
   <types>
       <members>AEH_Default_Navigation</members>
       <members>AEH_Default_User_Navigation</members>
       <name>NavigationMenu</name>
   </types>
   <types>
       <members>cbAPI_Experience_Hub</members>
       <name>NetworkBranding</name>
   </types>
   <!--
   <types>
       <members>API Experience Hub Member User</members>
       <name>Profile</name>
   </types>
   -->
   <version>60.0</version>
</Package>
----
.. In a VCS, create a development branch.
.. Download the metadata using the manifest created from the Salesforce sandbox organization. 
. Retrieve the metadata from Salesforce sandbox organization using Salesforce CLI commands:
.. Log in to the Salesforce sandbox organization.
+
[codeblock]
----
sf auth web login --instance-url=https://<SANBOX-INSTANCE_URL> --alias sandboxOrg
----
.. Edit the *config/package.xml* file before retrieving the metadata from the sandbox organization to retrieve the new metadata that you added.
+
Your sandbox organization can contain a lot of metadata from different products because it's a copy from the Salesforce production organization. API Experience Hub is a subset of it and it's specified in the `config/package.xml` file that was created when creating the Git repository in a previous step. 
+
.. If the portal contains branding images, add them in *ContentAsset* section in *config/package*. For example:
+
[codeblock]
----
...
<types>
    <members>homeroCompanyLogo</members>
    <members>homeroLoginBackground</members>
    <members>minionHomeBanner</members>
    <members>minionPageBanner</members>
    <name>ContentAsset</name>
</types>
...
----

.. Review the metadata and retrieve it by running this command:
+
[codeblock]
----
sf project retrieve start --source-dir force-app --target-org sandboxOrg
----       
.. Confirm the metadata and commit all the metadata changes into the Git repository, 
or you can modify the `config/package.xml` and repeat the process if some metadata is missing or not necessary.
. Move the API Experience Hub portal from the sandbox organization to the production organization:
.. Log in to the production organization:
+
[codeblock]
----
sf auth web login --instance-url=https://<ENTERPRISE-INSTANCE_URL> --alias productionOrg
----
+
Before installing the API Experience Hub Manage Package in your production organization, get the managed package version ID (SubscriberPackageVersionId) that's installed in the sandbox organization. 
+
.. Run the following command to get the managed package version ID. The `SubscriberPackageVersionId` field from the API Experience Hub managed package begins with *04t*:
+
[codeblock]
----
sf package installed list --target-org sandboxOrg --json
----
.. Install the API Experience Hub managed package in the production organization.

sf package install --package 04t... --target-org productionOrg --no-prompt --wait 30

Deploy API Experience Hub metadata in the Production Org

Previously we got API Experience Hub metadata from the Sandbox org and we committed it in a branch inside a Git repository, now there are a lot of possibilities to implement a CI/CD Pipeline using Jenkins or similar tools to deploy the metadata in the Production org, but no matter how simple or complex your process is, you have to deploy your metadata using a command similar to this:

sf project deploy start --source-dir force-app --target-org productionOrg


At this point all configurations were deployed in the Production org, and you are ready to connect this org with API Experience Hub
Configure API Experience Hub in Production Org

Goto Anypoint / API Experience Hub and connect the Salesforce Production organization (enterprise org)
Reuse the Portal that already exist (it was created when you deploy the metadata in this org)
Add assets to the Portal
Preview your portal
Publish your Portal

Useful Salesforce documentation links
    
Continuous Integration
Deploy an Experience Cloud Site from Sandbox to Production
Maintaining U     ser References



== See Also

* xref:access-management::environments.adoc[]
* xref:setting-up-the-api-portal.adoc[]
