= Managing Users 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

View and manage users, access requests from guest users, create and manage user groups, and manage how users login. Users can self-register for your portal by default. 

== Manage Portal Members
Manage portal members using the *Portal members* page. When a guest user's registration is approved, the user's name is added to the list of members. You can view a searchable list of current members and manage their accounts by enabling or disabling them and adding them to user groups.

=== View and Search for Members 
Find members by entering the member's name or email address in the *Search by name or email* box. 

=== Enable or Disable Access to Your Portal
When a user's access to the portal is approved in the *Pending registration requests* page, the *Enable portal access* slider is enabled in the *Portal members* page. Disable a user's access by moving the slider to off.

=== Assign Members to User Groups
Assign users to user groups to manage which APIs they can see in your portal. You can assign a user to multiple user groups.

. From the *Portal members* page, locate the member's name in the list and click *Assign user group*.
. Select one or more user groups to assign to the member and click *Apply*.

=== Change a Member's User Groups 
You can change which user groups a member is assigned to.

. From the *Portal members* page, locate the member's name in the list and click *Assign user group*.
. Select one or more user groups to assign to the member an click *Apply*.

== Manage Pending Registration Requests
Use the *Pending registration requests* page to approve or reject requests for users who registered to access the portal. You can view the user's name, email, registration date, and registration status of the users who register for access. By default, users are assigned to the Members profile. You can add them to the available user groups that can see specific APIs in the portal. The maximum pending user registration requests is 500.

When the registration is approved, the user is removed from the list on the *Pending registration requests* page and added to the list of members on the *Portal members* page. 

If the registration is rejected, the user is removed from the list and can't log in and access the portal.

=== Approve or Reject Member Registration
After a guest user registers for an account using self-registration, approve or reject the requests and assign the user to user groups. All users who self-register are assigned as members. You can assign member users to multiple user groups.

. Click *Pending registration requests*.
. To find a user, enter the user's name or email in the *Search by name or email* box.
. To assign the user to a user group:
.. Click *Members* and select one or more user groups.
.. Click *Apply*.
. Click *Approve* or *Reject*.

== Manage User Groups
Manage user groups using the *User groups* page to create and manage a group of users who can see specific APIs in your portal.   

=== Create User Groups
Create groups of users who can see specific APIs in the portal.

. From the *User groups* page, click *Create user group*.
. Enter a name for the group and an optional description, and click *Save*.


=== Delete User Groups
Delete user groups you don't need. Before deleting a user group, remove all users,  APIs, and the visibility for all API instances assigned to the user group. 

To delete a user group, from the *User groups* page, select a user group and click *Delete user group*.

=== Map User Groups to External Identity Providers
For users of a user group to log in to your portal using SSO, map the user group to an existing external identity provider.

To add the user group to the corresponding profile in API Experience Hub:

. From the *User groups* page, select a group.
. In the *External IdP groups* tab, click *+ Add group mapping*.
. Enter the group name, select an Salesforce identity provider name, and click *Save*.
+
To avoid login issues, ensure that you use the same group name and identity provider name configured for the identity provider. 


=== View APIs That User Groups Can See
View the APIs that are visible by a user group for portal members and also the APIs assigned only to a user group. The *APIs visible to the user group* tab shows all of the APIs that members of the portal can see.  

. From the *User groups* page, select a user group.
. Select the *APIs visible to the user group* tab.
. To see APIs assigned to the group only, move the *Show only APIs assigned to this group* slider to on.

To view or change an API's visibility, see xref:managing-apis.adoc#make-api-versions-visible[Make API Versions Visible].

=== Delete Identity Provider Groups
Remove the external identity provider groups that you don't need.

. From the *User groups* page, select a user group group.
. Select the *External IdP groups* tab.
. Locate the group in the list and click *Remove group*.

== Manage Login Settings
Disable or enable self-registration for external users and set up single sign-on for your portal using the *Login settings* page. Self-registration enables guest users to register themselves as members of your API portal. From the *Pending requests* page, you can see a list of pending requests from guest users who want to access your portal. 

=== Disable or Enable Self-Registration
By default, the ability for external users to self-register is enabled. This allows guest users to register, become a member, and access your portal site. Administrators can disable self-registration.

NOTE: Self-registration is for new users only. 
Existing users can't self-register. They must use an identity provider to access the portal.

To disable external user registration, from the *Login settings* page turn off the *Allow external user registration* option. 

To enable external registration again, turn on the *Allow external user registration* option.

=== Configuring Single Sign-On (SSO)
The *Single sign-on (SSO)* section provides information about how to set up your portal with SSO. For detailed instructions about configuring SSO, see xref:enabling-sso-for-your-portal.adoc[].

===  Manage Salesforce Identity Providers
When enabling SSO, you can add new Salesforce identity providers and delete the providers that you previously configured, and enable and disable them as needed. When the identity provider is enabled, users can log in to the portal using this identity provider.

To add a new identity provider or delete an existing one:

. From the *User management*, select *Login settings*.
. From the *Single sign-on (SSO)* section, scroll to the *Add Salesforce identity providers* section.
. Click *Select identity provider* and select an option from the dropdown menu. 
. Click *+ Add identity provider*.
+
The identity provider is added to the list.
. If you want to delete the identity provider, click *Delete*.

To enable or disable an identity provider: 

. From the *Single sign-on (SSO)* section, scroll to the *Add Salesforce identity providers* section.
. Move the slider to *Enabled* next to the name of the identity provider.
. If you want to disable the identity provider, move the slider to *Disable*.

== Next Steps
You can further customize and brand your portal using the xref:customizing-your-portal.adoc[Experience Builder] by clicking *Preview and publish your portal*.

== See Also

* xref:registering-for-access-to-portal.adoc[Registering to Access a Portal]





