=  Working With Sandboxes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Use Salesforce sandbox organizations to test your portal in a sandbox environment under the same conditions as your production environment. API Experience Hub enables you to manage separate deployment environments for your API portal. You can connect to multiple Salesforce sandbox organizations and switch between them. Manage Salesforce organizations from the *Manage your API portal* page by selecting sandbox environments that are available in the current Salesforce connection.  

When no sandbox organizations are available in the connected production organization, the Salesforce organization switch is disabled.
//screen capture of org switcher

== Before You Begin
Ensure that you have sandbox organizations already set up. See, https://help.salesforce.com/s/articleView?id=sf.data_sandbox_create.htm&type=5[Create a Sandbox] in the Salesforce documentation for more information.

== Manage Salesforce Organizations 

. In the *Manage your API portal* page, click the organization switch control. 
//screen capture of environment/sandbox switcher control
. To connect to a production organization, click *Connect production org* from the *Connected Salesforce Orgs* dialog.
. To switch to another a sandbox for the connected production organization, click *Switch to this org* from the *Connected Salesforce Orgs* dialog.
. To connect to a sandbox organization that is not connected, click *Connect*.
. To connect to a new sandbox organization, click *Connect new sandbox org*.
. To switch to a another sandbox organization, click *Switch to this org*.

== Manage Orphaned Sandboxes
If you connected to a sandbox that is not a child of the production org, the sandbox appears as an orphan. Orphan sandbox organizations occur when the connection to the production organization is disconnected and there are child sandbox organizations still connected.

== Manage Refreshed Sandbox Connections

== Delete Sandbox Organizations 

To delete a sandbox organizaton, see xref:https://help.salesforce.com/s/articleView?id=000383260&type=1[Delete a sandbox] from the Salesforce documentation.

== Deploy a Sandbox to Production
//from PRD - When the test in the lower environment is ready, deploy a subset of the Salesforce metadata using your CI/CD pipeline to a higher environment. The deployment process is outside of the scope of AEH and is done following the current company release cycles. Afterward, you can connect to the production instances (that will have a subset of the Salesforce metadata) to complete the installation and start curating APIs.
== See Also

* xref:acess-management::environments.adoc[]
* xref:setting-up-an-api-portal.adoc[]
