= Managing Expiring Certificates
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Connected applications enable a two-way connection between Anypoint Platform and Salesforce organizations. These connected apps are dependent on digital certificates for proper functionality. These certificates are time-bound and subject to expiration. However, API Experience Hub continues to function properly when a certificates expires.


AEH has a certificate for connecting the Anypoint Platform org to the Salesforce org and a certificate for the SF identity data.
== Required Permissions
Ensure you have the AEH Administrator perimssion.


== Manage Connection Certificate
A self-signed certificate is generated by the API Experience Hub to facilitate the linkage between an Anypoint Platform organization and a Salesforce organization during the connection phase. The certificate, along with the private key, is stored in Anypoint Secret Manager in PEM format. The expiration date of the certificate is determined using the subsequent expression:

The connection between Anypoint Platform and Salesforce remains operational after the certificate expires. The Salesforce organization does not send any notification to the Salesforce administer. When the certificate expires, 

The maximum number of certificates is 50. As a best practice, delete the renamed connected app 

. From Salesforce, click *Setup*.
. In the *Quick Find* box, enter *app management* and click *App Manager*.
. Delete the *Anypoint_AEH* connect app.
. Log in to Salesforce.
+
A new certificate is created and expires within 364 days.

== Create a New AEH Consumer Certificate 
The expiring or expired certificate cannot be deleted because it is used by the named credentials.

. Go to Salesforce and click *Setup* > *Security* > *Certificate and Key Management*.
. From the certificate that is expiring or is expired, click *Edit*.
. Enter *any name?*
. Click *Save*.
. Go to API Experience Hub.
+
The edited name triggers a diagnostic check to delete the certificate and creates a new one. 