= Prerequisites 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Verify that you have the following required accounts and access:

* Anypoint Platform organization in production
* Salesforce organization
* Organization Administrator of the main organization

If you do not have the required accounts and access, issues may occur during the Salesforce linking process when creating your API portal.

== Configure Administrator Permissions
Anypoint Platform comes with predefined permissions that you can set in Anypoint Access Management to provide users with different access levels. You can configure the permissions for administrators and Exchange viewers.
 
=== Before You Begin
Consider which user in your organization you want to perform the administrator tasks.


=== Grant the API Experience Hub Administrator Permission
Only the Organization Administrator can grant a user the API Experience Hub Administrator permission. Grant this permission when you want another user in your organization to perform the Salesforce linking process, create and curate the portal, manage the portal, and manage users.

To grant the API Experience Hub Administrator permission to a user:

. Log in to Anypoint Platform using an account with the Organization Administrator permission.
. Click *Access Management*.
. Click *Users*.
. Click the username of the user that you want to add the API Experience Hub Administrator permission. 
. Select *Permissions* and click *Add Permissions*.
. From the *Select permissions to add for this user* search box, enter *API Experience Hub Amin* and select the checkbox.
. Click the blue plus icon.

//=== Grant the API Experience Hub Portal Administrator Permission 

//If there is more than one users that manages the portal, you can grant another user within your organization the API Experience Hub Portal Administrator permission.

//. From *Access Management*, click *Users*.
//. Click the username of the user that you want to add the API Experience Hub Administrator permission. 
//. Select *Permissions* and click *Add Permissions*.
//. From the *Select permissions to add for this user* search box, enter *API Experience Hub Portal Amin* and select the checkbox.
//. Click the blue plus icon.

=== Grant the Exchange Viewer Permission

API Experience Hub Administrators can only add APIs to the portal that they have access to in Exchange. All administrators must have the Exchange Viewer permission to add APIs to the portal.

Once an API is added to the API portal, all admins can view the API in the portal regardless of their access to specific APIs.

To grant the Exchange Viewer permission to a user:

. From *Access Management*, click *Users*.
. Click the username of the user that you want to add the Exchange Viewers permission. 
. Select *Permissions* and click *Add Permissions*.
. From the *Select permissions to add for this user* search box, enter *Exchange Viewers* and select the checkbox.
. Click the blue plus icon.

== See Also
* xref:users-roles-and-permissions.adoc[Users, Roles, and Permissions]