= Simulating API Calls Using the Mocking Service
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The API mocking service enables you simulate the behavior of an API specification. The mocking service provides a test link to an API. The mocking service returns the responses (both HTTP status codes and example payloads) that are defined in your API specification, and is valuable for testing or for simply exploring how your API behaves.
When you add an endpoint to your API specification, API Designer automatically generates a link to the API that you can use in a browser. You can also enable a public link that can be shared with users outside of Anypoint Platform.
The mocking service is a feature of Anypoint Platform and runs continuously. You can run the mocking service from the text editor, the visual editor, and from Anypoint Exchange. You can simulate calls to the API in API Designer before publishing the API specification to Exchange or in Exchange after publishing the API specification.
If you specified a base URI (RAML) or base path (OAS), API Designer enables you to use either the base URI or the mocking service when simulating an API call. API Designer does not make any changes to your APIs.


== Before You Begin

You must have an API specification with at least one endpoint and one method in it.

== Simulate a Call to an API using an Internal URL
To access the internal URL, you must specify the authorization headers as part of the request URL. To test an API without supplying authorization headers, generate a mocking service public URL for this project. Mocking Service is the selected server in the *Try it* panel. 

. From the *Home* or the *APIs* page, select an API.
. From the API Console, select *Summary*.
. From the *Documentation* panel, click on the name of an end point.
//. Click one of the methods of your API, then click *Try it*.
. (Optional) Provide and query parameters you want to test.
. You can enter query parameters as name/value pairs.
. Click *Send*.
+
API Console displays the HTTP return code as specified in your API. Alternately, you can test the API by copying the Request URL and paste it into a web browser or Postman.