= Troubleshooting
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you encounter errors, refer to the following instructions for recovery.

== Cannot See Images in the Builder Preview That Were Uploaded When Creating the Portal
In the Builder preview, you cannot see the images that were uploaded when creating the portal because the shared user is not a member of any libraries.

To add the shared user as a member of the asset library:

. Log in to the Salesforce organization as a System Administrator.
. Click the *App Launcher*, enter *files* in the search box, and select *Files*. 
. Click *Libraries* in the navigation pane.
. Click *Asset Library* in the list.
. Click *Manage Members*. 
+ 
The *Manage Library Members* screen opens. 
. In the *Add Members* field, click the down arrow next to the stack icon and select *People*.
+
The *Add Members* field shows the *search people* box.
. Click in the *search people* box and select *Builder Preview*.
. In the *Access* field, select *Author*. 
. Click *Add* to allow the Builder Preview user to upload images in the Builder for later use.
+
The *Current Members* section shows the *Builder Preview* member and *Author* access.
. Close the screen.
+
. Confirm that the Builder Preview user can see the library images in the Builder. 
. Reload the page if the images are not showing up.


== Cannot Access the API Management Page to Disconnect Portal
 
The unlinking process deletes the configuration created during the linking process, connected apps, and IDPs in the Anypoint organization. This process does not delete your portal or uninstall the API Experience Hub package. Use this method if you want to create a portal using another Salesforce organization with the same Anypoint account.

To disconnect your portal:

. Run this command to get a token from Anypoint:
+
* US users:
+ 
[source,curl]
----
curl --location --request POST 'https://anypoint.mulesoft.com/accounts/login' \
--header 'Content-Type: application/json' \
--data-raw '{
"username": "Username",
"password": "Password"
}
' 
----
* EU users:
+
[source,curl]
----
curl --location --request POST 'https://eu1.anypoint.mulesoft.com/accounts/login' \
--header 'Content-Type: application/json' \
--data-raw '{
"username": "Username",
"password": "Password"
}     
'
----
. Run this command to extract the token:
+ 
[source,curl]
----
{
 "access_token": "TOKEN",
 "token_type": "bearer",
 "redirectUrl": "/home/"
}
----
. Run this command to get the connection ID from this request:
+
[source,curl]
----
curl --location --request GET 'https://anypoint.mulesoft.com/api-experience-hub/api/v1/connections' \
--header 'Authorization: Bearer [INSERT TOKEN HERE]'
----
+ 
For EU users, use `https://eu1.anypoint.mulesoft.com` in the request. 
. Extract the connection ID from this:
+
[source,curl]
----
[
 {
 "createdDate": "2022-12-06T17:27:53.705+00:00",
 "environment": "SANDBOX",
 "id": "[CONNECTION-ID]",
 "organizationId": "******",
 "targetOrganizationDomain": "******",
 "targetOrganizationId": "******",
 "type": "SALESFORCE",
 "updatedDate": "2022-12-06T17:27:53.705+00:00",
 "username": "******"
 }
]
----
. Run this command to delete the connection:
+
[source,curl]
----
curl --location --request DELETE 'https://anypoint.mulesoft.com/api-experience-hub/api/v1/connections/[CONNECTION-ID]' \
--header 'Authorization: Bearer [INSERT TOKEN HERE]' 
----
+
The connections is deleted. You can connect to a new connection to another Salesforce organization. We recommend deleting the browser cache or using a new incognito browser to have a fresh environment to start the linking process again.

== API Experience Hub Does Not Show on the Anypoint Platform Landing Page
If API Experience Hub does not show on the Anypoint Platform landing page, ensure that you are using the main organization. Contact the MuleSoft administrator to ensure that the entitlement is enabled.

== Error Occurs When Changing the Relax IP Restrictions Option 

In this release, IP restrictions for the connected app are not supported. By default, the IP Restrictions field is set to `Relax IP Restrictions`. If you have Trusted IP Ranges in your organization, they are bypassed by the connected app. To avoid errors, do not change the *IP Restrictions* field from `Relax IP Restrictions` because it produces errors when creating the portal. 

== Error Saving Changes to the Portal When an Object Has Validation Rules Activated

An error occurs when saving styling changes to the portal if an object has validation rules applied for standard objects that are created during the Salesforce linking process. 

Custom validation rules can be applied to several Salesforce objects, for example, account and user objects that cause linking and other processes to fail. 

The workaround is to bypass the validation rule for the Salesforce user who performs the linking process. 

NOTE: These instructions pertain to bypassing account object validation rules but can apply to bypassing other object custom validation rules.

. Create a custom permission:
.. From Salesforce, go to *Setup*, enter *custom permissions* in the Quick Find box, and select *Custom Permissions*.
.. Click *New* and enter the permission information:
+
* *Label*
+ 
Enter *Bypass Account Validation Rule*. 
+
* *Name* 
+
Click into the field to populate it with the label name with underscores.
+
* *Description*
+ 
Enter a description for the permission.
.. Click *Save*.

. Create a permission set and add the custom permission:
+ 
You can also use an existing permission set instead of creating a new one.

.. From *Setup*, enter *permission sets* in the Quick Find box and click *Permission Sets*.
.. Click *New* and enter the permission set information:
+
* *Label*
+ 
Enter *Bypass Account Validation Rule*. 
+
* *Name* 
+
Click into the field to populate it with the label name with underscores.
.. Click *Save*.
.. Click *Bypass Account Validation Rule* and select *Custom Permissions* from the *Apps* section.
.. From *Available Custom Permissions*, select *Bypass Account Validation*, click *Add*, and then click *Save*.
.. From the *Custom Permissions* list, select *Bypass Account Validation* and *Save*.
.. From *Object Manager*, select *Validation Rules*.
.. Select the object used for the validation rule and click *Edit*.
.. In the *Error Condition Formula* box, enter the following:
+
[codeblock]
----
AND (
  NOT($Permission.Bypass_Account_Validation),
  ISBLANK (Website)  
)
----
.. Click *Save*.

. Assign the permission set to the user performing the linking process:
+
This user must have the System Administrator profile to perform the linking process.
+
.. From *Setup*, enter *permission sets* in the Quick Find box and click *Permission Sets*.
.. Click *Bypass Account Validation Rule* and click *Manage Assignments*.
.. Click *Add Assignment*, select the user, and then click *Next*.
.. Click *Assign*.

== Error When Installing the Package During the Connection Process
If you encounter errors while installing the package during the  connecting to Salesforce process, you can review more details about the deployment status:

. From Salesforce, go to *Setup*.
. Click *Environments*. 
. Click *Deploy*.
. Click *Deployment Status*.
. Review the *Failed* and *Succeeded* sections.

== Linking Process Fails
The linking process fails when the user who executes the linking process has the Exchange Contributor role in a business group and this user does not have the System Administrator permission in that same business group. 

To resolve this issue, add the organization administrator permission to the user who is executing the Salesforce linking in the business group.

== Not Receiving Emails from Salesforce Experience Cloud
If you are not receiving emails from Salesforce Experience Cloud, disable the standard configuration by following these steps:

. Go to *Setup* > *Deliverability* > *Email Security Compliance*.
. Deselect *Enable compliance with standard email security mechanisms*.

== Contact MuleSoft Support
For professional services customizations, enhancement requests, and other help, contact your MuleSoft Customer Success representative.

To report issues or defects in API Experience Hub, submit a support case through the https://help.mulesoft.com[MuleSoft support portal].

The MuleSoft support team works closely with the Salesforce support team to coordinate work on any support tickets involving Salesforce technology.

Service-level agreements (SLAs) for support are available at the https://www.mulesoft.com/legal/support-maintenance-terms?_gl=1*9coixf*_ga*MTc1Mzc4OTg5Mi4xNjc3ODY5OTkw*_ga_HQLG2N93Q1*MTY4NTk5MDc4My4yNDAuMS4xNjg1OTkwODE0LjAuMC4w[MuleSoft Product Support and Maintenance Terms] page.
