= Troubleshooting
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you encounter errors, refer to how to report an issue and these explanations and instructions for recovery.

== Report an Issue
You can report an issue with API Experience Hub using email or Slack.

For email, send issues to aeh-pilot@mulesoft.com.

For Slack, follow these steps:

. In a Slack channel, click the lightning bolt icon.
. Click *AEH Report a Bug*.
. From the *Report a bug* form, complete the following fields:
+ 
* *Subject*: Enter a title for the issue, for example, cannot add an API from Exchange.
* *Steps to Reproduce*: Enter an explanation of how to reproduce this issue.
* *Severity*: Select a severity level from the list.
* *Customer Name*: Enter your first and last name.
. Click *Submit*.

== Not Receiving Emails from Salesforce Experience Cloud
If you are not receiving emails from Salesforce Experience Cloud, disable the standard configuration by following these steps:

. Go to *Setup* > *Deliverability* > *Email Security Compliance*.
. Unselect *Enable compliance with standard email security mechanisms*.

== Cannot View API Experience Hub on Anypoint Platform Landing Page
If API Experience Hub does not display on the Anypoint Platform landing page, ensure that you are using the main organization. Contact the Mulesoft administrator to ensure that the entitlement is enabled.

== Linking Process Fails

The linking process fails when the user who executes the linking process has the Exchange Contributor role in a business group and this user does not have the System Administrator permission in that same business group. 
+
To resolve this issue, add the organization administrator permission to the user who is executing the Salesforce linking in the business group.
+
