= Troubleshooting
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you encounter errors, refer to the following instructions for recovery.

== Cannot See Images in the Builder Preview that Were Uploaded When Creating the Portal
In the Builder preview, you cannot see the images that were uploaded when creating the portal because the shared user is not a member of any libraries.

To add the library to view the images:

. Log in to the Salesforce organization as a System Administrator.
. Click *App Launcher*, enter *files* in the search, and select *Files*. 
. In the *Files* page, click *Libraries*.
. Click *Asset Library* in the list of libraries.
. Click *Manage Members*. 
. In the *Manage Library Members* page, click the drop-down icon and select *People*.
+
The *Add Members* field shows *search people*.
. Enter *Builder* in the search and select the *Builder Preview* user. LeavePreview at access at Author to allow the builder preview user to upload images in the builder for later use
. Click *Add*.
+
The Builder Preview shows the list of Current Members.
. Close the page.Exit the modal.
+
. Confirm that you can see the library assets in the Builder. . Reload the page if it's not showing up.


== Cannot Access the API Management Page to Disconnect Portal
 
The unlinking process deletes the configuration created during the linking process, connected apps, and IDPs in the Anypoint organization. This process does not delete your portal or uninstall the API Experience Hub package. Use this method if you want to create a portal using another Salesforce organization with the same Anypoint account.

To disconnect your portal:

. Run this command to get a token from Anypoint:
+
* US users:
+ 
[source,curl]
----
curl --location --request POST 'https://anypoint.mulesoft.com/accounts/login' \
--header 'Content-Type: application/json' \
--data-raw '{
"username": "Username",
"password": "Password"
}
' 
----
* EU users:
+
[source,curl]
----
curl --location --request POST 'https://eu1.anypoint.mulesoft.com/accounts/login' \
--header 'Content-Type: application/json' \
--data-raw '{
"username": "Username",
"password": "Password"
}     
'
----
. Run this command to extract the token:
+ 
[source,curl]
----
{
 "access_token": "TOKEN",
 "token_type": "bearer",
 "redirectUrl": "/home/"
}
----
. Run this command to get the connection ID from this request:
+
[source,curl]
----
curl --location --request GET 'https://anypoint.mulesoft.com/api-experience-hub/api/v1/connections' \
--header 'Authorization: Bearer [INSERT TOKEN HERE]'
----
+ 
For EU users, use `https://eu1.anypoint.mulesoft.com` in the request. 
. Extract the connection ID from this:
+
[source,curl]
----
[
 {
 "createdDate": "2022-12-06T17:27:53.705+00:00",
 "environment": "SANDBOX",
 "id": "[CONNECTION-ID]",
 "organizationId": "******",
 "targetOrganizationDomain": "******",
 "targetOrganizationId": "******",
 "type": "SALESFORCE",
 "updatedDate": "2022-12-06T17:27:53.705+00:00",
 "username": "******"
 }
]
----
. Run this command to delete the connection:
+
[source,curl]
----
curl --location --request DELETE 'https://anypoint.mulesoft.com/api-experience-hub/api/v1/connections/[CONNECTION-ID]' \
--header 'Authorization: Bearer [INSERT TOKEN HERE]' 
----
+
The connections is deleted. You can connect to a new connection to another Salesforce organization. We recommend deleting the browser cache or using a new incognito browser to have a fresh environment to start the linking process again.

== API Experience Hub Does Not Show on the Anypoint Platform Landing Page
If API Experience Hub does not show on the Anypoint Platform landing page, ensure that you are using the main organization. Contact the MuleSoft administrator to ensure that the entitlement is enabled.

== Error Occurs When Changing the Relax IP Restrictions Option 

In this release, IP restrictions for the connected app are not supported. By default, the IP Restrictions field is set to `Relax IP Restrictions`. If you have Trusted IP Ranges in your organization, they are bypassed by the connected app. To avoid errors, do not change the *IP Restrictions* field from `Relax IP Restrictions` because it produces errors when creating the portal. 

== Error Saving Changes to the Portal When an Object has Validation Rules Activated

An error occurs when saving styling changes to the portal if an object has validation rules applied for standard objects that are created during the Salesforce linking process. 

The workaround is to deactivate the validation rule, save the styling changes, then reactive the validation rule: 

. Navigate to *Setup* > *Object Manager*.
. Select *Validation Rules*.
. Search for the object with the validation rule.
. Click *Edit* next to the rule you want to deactivate.
. Deselect the *Active* checkbox.
. Click *Save*.
. Navigate back to API Experience Hub and click *Try again* in the error message.
. Click *Save* to save your style selections.
. Repeat steps 1 through 4.
. Select the *Active* checkbox and click *Save*.

== Error When Installing the Package During the Connection Process
If you encounter errors while installing the package during the  connecting to Salesforce process, you can review more details about the deployment status:

. From Salesforce, go to *Setup*.
. Click *Environments*. 
. Click *Deploy*.
. Click *Deployment Status*.
. Review the *Failed* and * Succeeded* sections.

== Linking Process Fails
The linking process fails when the user who executes the linking process has the Exchange Contributor role in a business group and this user does not have the System Administrator permission in that same business group. 

To resolve this issue, add the organization administrator permission to the user who is executing the Salesforce linking in the business group.

== Not Receiving Emails from Salesforce Experience Cloud
If you are not receiving emails from Salesforce Experience Cloud, disable the standard configuration by following these steps:

. Go to *Setup* > *Deliverability* > *Email Security Compliance*.
. Deselect *Enable compliance with standard email security mechanisms*.

== Contact MuleSoft Support
For professional services customizations, enhancement requests, and other help, contact your MuleSoft Customer Success representative.

To report issues or defects in API Experience Hub, submit a support case through the https://help.mulesoft.com[MuleSoft support portal].

The MuleSoft support team works closely with the Salesforce support team to coordinate work on any support tickets involving Salesforce technology.

Service-level agreements (SLAs) for support are available at the xref:https://www.mulesoft.com/legal/support-maintenance-terms?_gl=1*9coixf*_ga*MTc1Mzc4OTg5Mi4xNjc3ODY5OTkw*_ga_HQLG2N93Q1*MTY4NTk5MDc4My4yNDAuMS4xNjg1OTkwODE0LjAuMC4w[MuleSoft Product Support and Maintenance Terms] page.
