= Viewing API Details
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To view the API Details page, select an API from the Home or APIs page of the portal. 
// add screen captures
The API Details page includes the following information about an API:

* *Name*
+
Name of the API.
* *Type*
+ 
The API type can be AsyncAPI, HTML, REST, or SOAP.
* *Contact email*
+
The email of the contact for the API.

* *Categories*
+
The name and value of the predefined category this API belongs to. APIs can have multiple categories. Categories are used to organize APIs into groups to improve browsing and discovery. 
* *Tags*
+
The name of a predefined keyword associated with this API. APIs can have multiple tags. Tags are used to filter search results. 
* *Description*
+
A description of the API.

* *Asset version*
+
The version of the API.
* *Version state*
+
The lifecycle state of this API. Lifecycle states are development, stable, and deprecated.
* *Instances*
+
The count of instances of the API.
* *Clients *
+
The number of client applications of the API.

The API Console is located in the API Details page. The console component is interactive and shows information about API specifications and their methods. Endpoints are displayed in alphabetical order. See xref:api-console-specification-and-documentation.adoc[API Console Specification and Documentation] for more information.

== View Instances Information and Copy the URL
To view the name and URL of an instance and copy the URL:

. Click *View instances*.
. Click the copy icon.
. Click *Close*.


== See Also

* xref:requesting-access-to-an-api-instance.adoc[Requesting Access to an API Instance]