= Configuring Feed Tracking
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Add Chatter and Feed components to engage with your portal community. Portal members can collaborate with your organization, seek expert advice, and review relevant discussions


== Enable Feed Tracking

. Go to Salesforce and click *Setup*.
. In the Quick Find box, enter *feed tracking* and select *Feed Tracing*.
. Select *Community Asset* and *Enable Feed Tracking*.
. Click *Save*.



== Hide Tabs
By default, the *API details* page displays the Post, Poll, or Question tabs. Hide  tabs that you don't want to show.

. Go to Salesforce and click *Setup*.
. In the *Quick Find* box, enter *publisher layouts* and select *Publisher Layouts*. 
. Click *Edit*.
. Remove the tabs that you don’t want to show.
. Click *Save*.


== Allow Members to See Other Member Profiles
Enable members to see the name, title, company name, other information of other members, and follow and message each other.

. Go to Salesforce and click *Setup*.
. In the *Quick Find* box, enter *sharing settings* and select *Sharing Settings*. 
. Click *Edit*.
. Enable *Portal User Visibility*.
. Click *Save*.

== Show Members First and Last Names
By default member nicknames are shown. To show first and last name of members:

. Go to Salesforce and click *Workspaces*.
